# Generated by Django 4.2.9 on 2024-02-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appvincartapp', '0006_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
