# Generated by Django 4.2.9 on 2024-02-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appvincartapp', '0007_alter_customer_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='category_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Stock',
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('out_of_stock', 'Out of Stock')], default='in_stock', max_length=20),
        ),
    ]
