# Generated by Django 4.2.9 on 2024-02-07 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appvincartapp', '0008_rename_category_product_category_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stock',
            new_name='Stock',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
    ]
