# Generated by Django 4.2.9 on 2024-02-08 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appvincartapp', '0009_rename_stock_product_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10),
        ),
    ]
