# Generated by Django 4.2.9 on 2024-02-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='uploads/products/')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('colors', models.CharField(blank=True, default='black', max_length=100, null=True)),
                ('Stock', models.CharField(choices=[('in_stock', 'In Stock'), ('out_of_stock', 'Out of Stock')], default='in_stock', max_length=20)),
            ],
        ),
    ]
